"""add notification_enabled flag

Revision ID: 6ba36bca4f0d
Revises: d266d71f9692
Create Date: 2026-02-23 18:27:10.347937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba36bca4f0d'
down_revision: Union[str, None] = 'd266d71f9692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'notification_enabled')
    op.drop_column('projects', 'notification_enabled')
    # ### end Alembic commands ###
